openapi: 3.0.0
info:
  title: API de Clientes
  description: Documentación de la API para la gestión de clientes con el uso de ApiKey.
  version: 1.0.0
servers:
  - url: https://apikey-dev.onrender.com/apiV1/
    description: Servidor en Render

paths:
  /client:
    post:
      summary: Crear un nuevo cliente
      description: Crea un nuevo cliente asociado a un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID del usuario.
                clientData:
                  type: object
                  description: Datos del cliente.
      responses:
        '201':
          description: Cliente creado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
                  clientData:
                    type: object
        '400':
          description: Error en la solicitud.
        '404':
          description: Usuario no encontrado.

    get:
      summary: Obtener todos los clientes
      description: Obtiene todos los clientes asociados a un usuario.
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: ID del usuario.
      responses:
        '200':
          description: Lista de clientes obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    clientData:
                      type: object
        '400':
          description: Error en la solicitud.
        '404':
          description: Usuario no encontrado.

  /client/{id}:
    get:
      summary: Obtener un cliente por ID
      description: Obtiene un cliente específico por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del cliente.
      responses:
        '200':
          description: Cliente obtenido correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  clientData:
                    type: object
        '400':
          description: Error en la solicitud.
        '404':
          description: Cliente no encontrado o no autorizado.

    put:
      summary: Actualizar un cliente por ID
      description: Actualiza los datos de un cliente específico por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del cliente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientData:
                  type: object
                  description: Nuevos datos del cliente.
      responses:
        '200':
          description: Cliente actualizado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  id:
                    type: string
                  clientData:
                    type: object
        '400':
          description: Error en la solicitud.
        '404':
          description: Cliente no encontrado o no autorizado.

    delete:
      summary: Eliminar un cliente por ID
      description: Elimina un cliente específico por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del cliente.
      responses:
        '200':
          description: Cliente eliminado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Error en la solicitud.
        '404':
          description: Cliente no encontrado o no autorizado.

  /auth/register:
    post:
      summary: Registrar un nuevo usuario
      description: Registra un nuevo usuario en la base de datos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuario registrado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  secretKey:
                    type: string
        '400':
          description: Usuario ya existe o datos faltantes.
        '422':
          description: Error al procesar la contraseña.

  /auth/getKey:
    post:
      summary: Obtener la clave secreta
      description: Obtiene la clave secreta de un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Clave secreta obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  secretKey:
                    type: string
        '400':
          description: Datos faltantes o error en la solicitud.
        '401':
          description: Credenciales incorrectas.
        '404':
          description: Usuario no encontrado.

  /auth/updateSecretKey:
    post:
      summary: Actualizar la clave secreta
      description: Actualiza la clave secreta de un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Clave secreta actualizada correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  secretKey:
                    type: string
        '400':
          description: Datos faltantes o error en la solicitud.
        '401':
          description: Contraseña incorrecta.
        '404':
          description: Usuario no encontrado.
        '409':
          description: Error al actualizar la clave secreta.

  /auth/updateUser:
    post:
      summary: Actualizar usuario
      description: Actualiza los datos de un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                newUsername:
                  type: string
                newPassword:
                  type: string
      responses:
        '200':
          description: Usuario actualizado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  secretKey:
                    type: string
        '400':
          description: Datos faltantes o nombre de usuario ya en uso.
        '401':
          description: Credenciales incorrectas.
        '422':
          description: Error al actualizar el usuario.

  /auth/deleteUser:
    post:
      summary: Eliminar usuario
      description: Elimina un usuario y sus clientes asociados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Usuario y clientes eliminados correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Datos faltantes o error en la solicitud.
        '401':
          description: Credenciales incorrectas.
        '404':
          description: Usuario no encontrado.
        '422':
          description: Error al eliminar el usuario.